all:
  children:

    swarm_manager:
      hosts:

        wing1.pterodactyl.diesel.net:
          timezone: America/Los_Angeles
          wings_uid: 1003 # automation
          wings_gid: 1004 # automation
          sftp_port: 2022
          game_server_port_start: 27000
          game_server_port_end: 27099
          
          # just copy/paste what the panel spits out for you:
          config: |
            debug: false
            uuid: 9ac1e619-c41d-479c-a6bb-ce90cef2a6fa
            token_id: 3NuCoqqQX2rbFfZV
            token: YVbkrOjFmChjuFYf5Fxch5KGQgS7zhWdL2iLkv2FkJWY6RjFFOWgYh4GFEzjwwOw
            api:
              host: 0.0.0.0
              port: 443
              ssl:
                enabled: false
                cert: /etc/letsencrypt/live/wing1.pterodactyl.diesel.net/fullchain.pem
                key: /etc/letsencrypt/live/wing1.pterodactyl.diesel.net/privkey.pem
              upload_limit: 1024
            system:
              data: /var/lib/pterodactyl/volumes
              sftp:
                bind_port: 2022
            allowed_mounts: []
            remote: 'https://pterodactyl.kiwi-labs.net'
            allowed_origins: [\'*.diesel.net', '*.kiwi-labs.net']

  vars:

    ansible_user: automation
    ansible_python_interpreter: /usr/bin/python3
