version: '3.8'

services:
  {{ inventory_hostname | split('.') | first }}:
    image: ghcr.io/pterodactyl/wings:v1.11.8
    networks:
      - {{ traefik_network }}
    ports:
      - {{ sftp_port }}:{{ sftp_port }}
    environment:
      TZ: "{{ timezone }}"
      WINGS_UID: {{ wings_uid }}
      WINGS_GID: {{ wings_gid }}
      WINGS_USERNAME: pterodactyl
    volumes:
      - "/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "{{ config_dir }}:/etc/pterodactyl/"

      # the "src" directories (left side) of the volumes below MUST be exactly these paths.. 
      # perhaps you can change this in the node's `config.yml` ?
      # Not sure why it would be implemented this way
      - "/var/lib/pterodactyl/:/var/lib/pterodactyl/"
      - "/var/log/pterodactyl/:/var/log/pterodactyl/"

      # This directory is required for the stack to start yet Ubuntu clears it with every reboot..
      # see `.ansible/deploy.yaml#29`
      - "/tmp/pterodactyl/:/tmp/pterodactyl/"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.{{ app_name }}.loadbalancer.server.port=443
        
        - traefik.http.middlewares.{{ app_name }}-cors.headers.accesscontrolallowcredentials=true
        - traefik.http.middlewares.{{ app_name }}-cors.headers.accesscontrolallowheaders=*
        - traefik.http.middlewares.{{ app_name }}-cors.headers.accesscontrolallowmethods=*
        - traefik.http.middlewares.{{ app_name }}-cors.headers.accesscontrolalloworiginlist=*

        - traefik.http.routers.diesel-{{ app_name }}.rule=Host(`{{ diesel_host }}`)
        - traefik.http.routers.diesel-{{ app_name }}.tls.certresolver=step-ca
        - traefik.http.routers.diesel-{{ app_name }}.service={{ app_name }}@docker
        - traefik.http.routers.diesel-{{ app_name }}.middlewares={{ app_name }}-cors@docker

        - traefik.http.routers.kiwi-{{ app_name }}.rule=Host(`{{ kiwi_host }}`)
        - traefik.http.routers.kiwi-{{ app_name }}.middlewares={{ app_name }}-auth@docker
        - traefik.http.routers.kiwi-{{ app_name }}.tls.certresolver=cloudflare
        - traefik.http.routers.kiwi-{{ app_name }}.tls.domains[0].main={{ '.'.join( kiwi_host.split('.')[1:] ) }}
        - traefik.http.routers.kiwi-{{ app_name }}.tls.domains[0].sans=*.{{ '.'.join( kiwi_host.split('.')[1:] ) }}
        - traefik.http.routers.kiwi-{{ app_name }}.service={{ app_name }}-backend@docker

networks:
  {{ traefik_network }}:
    external: true
