version: '3.8'

services:
  {{ node_name }}:
    image: ghcr.io/pterodactyl/wings:v1.11.3
    networks:
      - {{ traefik_network }}
      # - pterodactyl_nw
    ports:
      - 2022:2022
    environment:
      #GODEBUG: netdns=go+2
      TZ: "{{ timezone }}"
      WINGS_UID: {{ wings_uid }}
      WINGS_GID: {{ wings_gid }}
      WINGS_USERNAME: pterodactyl
    volumes:
      - "/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "{{ config_dir }}:/etc/pterodactyl/"
      - "{{ data_dir }}/var:/var/lib/pterodactyl/"
      - "{{ data_dir }}/logs:/var/log/pterodactyl/"
      - "{{ data_dir }}/temp:/tmp/pterodactyl/"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.{{ repository }}.loadbalancer.server.port=443
        - traefik.http.routers.{{ repository }}.rule=Host(`{{ inventory_hostname }}`)
        - traefik.http.routers.{{ repository }}.tls.certresolver=step-ca
        - traefik.http.routers.{{ repository }}.service={{ repository }}

networks:
  {{ traefik_network }}:
    external: true
  # pterodactyl_nw:
  #   ipam:
  #     config:
  #       - subnet: 10.0.200.0/24
