- hosts: swarm_manager
  roles:
    - application
    - traefik
  
  tasks:

    - include_role:
        name: application
        tasks_from: make_data_dir

    - include_role:
        name: application
        tasks_from: make_config_dir

    - name: Render Node's config.yml
      file:
        content: '{{ config_file }}'
        dest: '{{ config_dir }}/config.yml'

    # - file:
    #     path: '{{ data_dir }}'
    #     owner: '472'
    #     group: '0'
    #     mode: u=rwx,g=rx
    #   become: yes

    - name: make data subdirs
      file:
        path: '{{ data_dir }}/{{ item }}'
        state: directory
        #owner: '472'
        #group: '0'
        #mode: u=rwx,g=rx
      #become: yes
      loop:
        - var
        - logs
        - temp

    - include_role:
        name: docker
        tasks_from: stack_deploy
