- hosts: swarm_manager
  roles:
    - application
    - traefik
  
  tasks:

    - include_role:
        name: application
        tasks_from: make_config_dir

    - name: Render Node's config.yml
      copy:
        content: '{{ config }}'
        dest: '{{ config_dir }}/config.yml'

    - name: Ensure directories exist
      file:
        path: '{{ item }}'
        state: directory
        owner: 'automation'
        group: 'automation'
      become: yes
      loop:
        - /var/lib/pterodactyl
        - /var/log/pterodactyl
        - /tmp/pterodactyl

    - name: Ensure /tmp/pterodactyl exists after reboot
      copy:
        content: |
          d /tmp/pterodactyl 0755 automation automation
        dest: /usr/lib/tmpfiles.d/pterodactyl.conf
      become: yes

    - name: Allow port {{ sftp_port }} (SFTP) for the wings agent
      ufw:
        rule: allow
        port: '{{ sftp_port }}'
        proto: any
      become: yes

    - name: Allow ports {{ game_server_port_start }}-{{ game_server_port_end }} (TCP) for the game servers
      ufw:
        rule: allow
        port: '{{ game_server_port_start }}:{{ game_server_port_end }}'
        proto: tcp
      become: yes

    - name: Allow ports {{ game_server_port_start }}-{{ game_server_port_end }} (UDP) for the game servers
      ufw:
        rule: allow
        port: '{{ game_server_port_start }}:{{ game_server_port_end }}'
        proto: udp
      become: yes

    - name: Reload Firewall and enable at boot
      ufw:
        state: enabled
        policy: deny
      become: yes

    - include_role:
        name: docker
        tasks_from: network_create
      vars:
        docker_network: pterodactyl_nw

    - include_role:
        name: docker
        tasks_from: stack_deploy
