- hosts: swarm_manager
  roles:
    - application
    - traefik
  
  tasks:

    

    - include_role:
        name: application
        tasks_from: make_config_dir

    - name: Render Node's config.yml
      copy:
        content: '{{ config }}'
        dest: '{{ config_dir }}/config.yml'

    - name: Ensure directories exist
      file:
        path: /var/lib/pterodactyl/
        state: directory
        owner: 'automation'
        group: 'automation'
      become: yes

    - name: Ensure directories exist
      file:
        path: /var/log/pterodactyl/
        state: directory
        owner: 'automation'
        group: 'automation'
      become: yes

    - name: Ensure directories exist
      file:
        path: /tmp/pterodactyl
        state: directory
        owner: 'automation'
        group: 'automation'
      become: yes

    # - include_role:
    #     name: application
    #     tasks_from: make_data_dir

    # - name: make data subdirs
    #   file:
    #     path: '{{ data_dir }}/{{ item }}'
    #     state: directory
    #     owner: 'automation'
    #     group: 'automation'
    #     mode: u=rwx,g=rx
    #   become: yes
    #   loop:
    #     - var
    #     - logs
    #     - temp

    - include_role:
        name: docker
        tasks_from: stack_deploy
